### Create a new patient
POST localhost:4000/patients/new
Content-Type: application/json

{
  "name": "Yami Gautum",
  "email": "yami.gautum@example.com",
  "address": "Juhu Beach",
  "dateOfBirth": "1990-03-12",
  "registeredDate": "2025-04-18"
}

###