### Create a new patient
POST localhost:4000/patients/new
Content-Type: application/json

{
  "name": "Gaurav Salvi",
  "email": "gaurav.salvi@example.com",
  "address": "Borivali East",
  "dateOfBirth": "2001-04-01",
  "registeredDate": "2025-06-24"
}

###