### Update existing patient
PUT localhost:4000/patients/update/ba4d502e-3bad-49dd-ad62-2762de07f76a
Content-Type: application/json

{
  "name": "Gaurav Salvi Updated",
  "email": "gaurav.salvi@example.com",
  "address": "Borivali West",
  "dateOfBirth": "2001-04-01",
  "registeredDate": "2025-06-24"
}
